apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chart1
spec:
  destination:
    name: ''
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: chart1
    repoURL: https://github.com/shiveshabhishek/forjpmc.git
    targetRevision: retry-options
    helm:
      valueFiles: []
      parameters:
        - name: env.name
          value: charttest
  sources: []
  project: default
  syncPolicy: {}
    # automated:
    #   prune: true
    #   selfHeal: true

