apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-example
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/gopaljayanthi/forjpmc.git
          revision: master
          files:
          - path: "addons/cmapp/dev/config.json"
      - list:
          elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            values:
              namespace: ns1
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            values:
              namespace: ns2
  template:
    metadata:
      name: '{{.name}}-{{.values.namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/gopaljayanthi/forjpmc.git
        targetRevision: HEAD
        path: configmap
      destination:
        server: '{{.url}}'
        namespace: '{{.values.namespace}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PrunePropagationPolicy=orphan
